# P6Spy ????

# ???????????SQL Server?
realdriver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ?????????
# ????info?debug?error?warn?statement?commit?rollback?result?batch
filter=true
logTypes=statement,result

# ??????????? SQL ??
logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat
appender=com.p6spy.engine.spy.appender.Slf4JLogger
dateformat=yyyy-MM-dd HH:mm:ss

# ????? SQL ???true = ?????
logFormat=statement
stacktrace=false


